steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-east1-docker.pkg.dev/$PROJECT_ID/my-repository/hello-cloudbuild-dev:v1.0', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-east1-docker.pkg.dev/$PROJECT_ID/my-repository/hello-cloudbuild-dev:v1.0']

- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'set'
  - 'image'
  - 'deployment/development-deployment'
  - 'dev-container=us-east1-docker.pkg.dev/$PROJECT_ID/my-repository/hello-cloudbuild-dev:v1.0'
  - '-n'
  - 'dev'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-east1-d'
  - 'CLOUDSDK_CONTAINER_CLUSTER=hello-cluster'

options:
  logging: CLOUD_LOGGING_ONLY

